swagger: '2.0'
info:
  version: 2.0.0
  title: Scurri API
  description: |
    The Scurri Platform API is a RESTful web service that offers import and
    update functionality for shipments, documents and manifests.
host: sandbox.scurri.co.uk
basePath: /api/2.0.0
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  basic:
    type: basic
paths:
  '/company/{company_slug}/shipments/{identifier}/allocate':
    post:
      description: |
        ### Service allocation.
        Use this endpoint to allocate a service to a shipment.
        The endpoint supports two scenarios:

        1) Allocate a shipment to specific carrier and service, the same way
          as you allocate manually in the Scurri UI.

        2) Allocate using rules.

        #### Manual allocation
        To do the manual allocation, you have to specify `carrier` and
        `service` fields at least.

        To use `shipment_method` field does not make sense in this scenario,
        and it will not have any effect.

        #### Allocation using rules
        To do allocation using rules, please do not specify `carrier` and
        `service` fields.

      operationId: allocateShipment
      parameters:
        - in: path
          name: company_slug
          type: string
          required: true
          description: Slug of your company
          default: api-test-company
        - in: path
          name: identifier
          type: string
          required: true
          description: Identifier of a shipment
        - in: body
          name: service allocation request
          description: Service allocation fields. All fields are optional.
          schema:
            $ref: '#/definitions/ServiceAllocation'
          required: false
      responses:
        '200':
          description: Response of service allocation result
          schema:
            $ref: '#/definitions/ServiceAllocationResult'
        default:
          description: error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ServiceAllocation:
    properties:
      carrier:
        type: string
        description: Carrier name, use it only for manual allocation.
      service:
        type: string
        description: Service identifier, use it only for manual allocation.
      shipment_method:
        type: string
        description: Order shipment method, used by Rules only.
      package_type:
        type: string
        description: Service package type.
      enhancements:
        type: object
        description: Map of service enhancements.
      incoterms_rule:
        type: string
        description: Incoterms rule, also known as customs invoice type in
          our V1 API.
    type: object
    example:
      carrier: Generic Carrier
      service: Generic Domestic Service GDOM
  ServiceAllocationResult:
    properties:
      status:
        type: string
      message:
        type: string
      carrier:
        type: string
      service:
        type: string
      enhancements:
        type: object
      incoterms_rule:
        type: string
      package_type:
        type: string
    required:
    - message
    - status
    type: object
  Error:
    required:
      - error
    properties:
      error:
        type: string
